from pathlib import Path
import json, re
root=Path('.')
idx=root/'app/src/main/assets/index.html'
s=idx.read_text(encoding='utf-8')
s=s.replace('v1.2.8','v1.2.9')
css=r'''\n/* ===== v1.2.9 native-scroll authoritative handset layer ===== */\n@media(max-width:700px){\n  html,body,body.bookmode,#bookReader,.book-shell,.book-stage,.book-page{position:static!important;width:100%!important;max-width:100%!important;min-width:0!important;height:auto!important;min-height:0!important;max-height:none!important;margin:0!important;overflow:visible!important;transform:none!important;contain:none!important;touch-action:auto!important}\n  body.bookmode .book-toolbar{display:none!important}\n  body.bookmode .book-page{padding:18px 14px 36px!important;border:0!important;box-shadow:none!important;background:#fffdf8!important}\n  body.bookmode .book-page::before{display:none!important}\n  body.bookmode .book-page *{box-sizing:border-box;max-width:100%}\n  body.bookmode .page-number{position:static!important;display:block!important;margin:26px 0 4px!important;text-align:center!important;color:#7c827f!important}\n  body.bookmode .book-page.turn-next,body.bookmode .book-page.turn-prev{animation:none!important}\n  body.visual-focus .book-page .lesson>*{display:none!important}\n  body.visual-focus .book-page .lesson>h3,body.visual-focus .book-page .lesson>.naturalplate,body.visual-focus .book-page .lesson>.explainer,body.visual-focus .book-page .lesson>.ta-figure-group,body.visual-focus .book-page .lesson>figure{display:block!important}\n  body.visual-focus .book-page .lesson>.ta-block{display:none!important}\n  .figure-lightbox:not(.open){pointer-events:none!important}\n}\n'''
s=s.replace('</style><meta content="#1f6552"',css+'\n</style><meta content="#1f6552"',1)
anchor='let BOOK_PAGES=[],BOOK_TITLES=[],BOOK_TYPES=[],BOOK_CATALOG=[];'
bridge="""function reportAndroidContentHeight(){\n  try{\n    if(window.AndroidHost&&typeof window.AndroidHost.setContentHeight==='function'){\n      requestAnimationFrame(()=>requestAnimationFrame(()=>{\n        const h=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.getElementById('bookPage')?.scrollHeight||0);\n        window.AndroidHost.setContentHeight(Math.ceil(h));\n      }));\n    }\n  }catch(e){}\n}\nwindow.addEventListener('load',()=>setTimeout(reportAndroidContentHeight,50));\n"""
s=s.replace(anchor,bridge+anchor,1)
s=s.replace("if(typeof window.placeApkFooterOnFinalPage==='function')window.placeApkFooterOnFinalPage();","if(typeof window.placeApkFooterOnFinalPage==='function')window.placeApkFooterOnFinalPage();\n    reportAndroidContentHeight();",1)
old="""      var page=document.getElementById('bookPage');if(page)page.scrollLeft=0;\n    });\n  }\n}"""
new="""      var page=document.getElementById('bookPage');if(page)page.scrollLeft=0;\n      reportAndroidContentHeight();\n    });\n  }\n}"""
s=s.replace(old,new,1)
insert="""\nfunction toggleVisualFocusNative(){\n  const page=document.getElementById('bookPage');\n  const has=!!page?.querySelector('.naturalplate,.explainer,.ta-figure-group,figure,img,svg');\n  if(!has)return 'none';\n  document.body.classList.toggle('visual-focus');\n  reportAndroidContentHeight();\n  return document.body.classList.contains('visual-focus')?'on':'off';\n}\n"""
s=s.replace('function toggleText(){',insert+'\nfunction toggleText(){',1)
idx.write_text(s,encoding='utf-8')

g=root/'app/build.gradle'; t=g.read_text(); t=t.replace('versionCode 10208','versionCode 10209').replace("versionName '1.2.8'","versionName '1.2.9'"); g.write_text(t)
cat=root/'app/src/main/assets/book-catalog.json'; j=json.loads(cat.read_text()); j['version']='1.2.9'; cat.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
mp=root/'verification/app-build-metadata.json'; m=json.loads(mp.read_text()); m['version_name']='1.2.9';m['version_code']=10209;m['app_version']='1.2.9';m['content_revision']='v1.2.9 native Android ScrollView host + measured WebView height; content unchanged';m['content_revision_manifest']='verification/content-revision-manifest-v1.2.9.json';mp.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
srcm=root/'verification/content-revision-manifest-v1.2.8.json'; m=json.loads(srcm.read_text());m['release']='1.2.9';m['previous_release']='1.2.8';m['purpose']='Native ScrollView host to make vertical scrolling independent of WebView touch scrolling; deterministic visual mode.';m['content_change']=False;m['reader_changes']=['Native Android ScrollView owns vertical scrolling','WebView expands to measured document height via local JavascriptInterface','Book page number is normal-flow on phones','Visual button reports no-visual pages and toggles deterministic visual-only mode','Next/Previous/Contents await page rendering and reset native scroll'];(root/'verification/content-revision-manifest-v1.2.9.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
ver=root/'tools/verify_content_integrity.py'; v=ver.read_text().replace('content-revision-manifest-v1.2.8.json','content-revision-manifest-v1.2.9.json').replace("'1.2.8'","'1.2.9'").replace('versionCode 10208','versionCode 10209').replace('v1.2.8','v1.2.9');ver.write_text(v)
